TWEAK_NAME = BannerStatus
BannerStatus_FILES = Tweak.xm
BannerStatus_FRAMEWORKS = UIKit CoreGraphics QuartzCore
BannerStatus_LIBRARIES = substrate
BannerStatus_LDFLAGS = -L$(THEOS_PROJECT_DIR)/tweak/lib -lmarquee
BannerStatus_CFLAGS = -I../include

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
