include theos/makefiles/common.mk

TWEAK_NAME = TinyBar
TinyBar_FILES = Tweak.xm
TinyBar_FRAMEWORKS = UIKit CoreGraphics QuartzCore
TinyBar_LIBRARIES = substrate
TinyBar_LDFLAGS = -L$(THEOS_PROJECT_DIR)/tweak/lib -lmarquee

include $(THEOS_MAKE_PATH)/tweak.mk
