#define TLog(format, ...) NSLog(@"TinyBar: %@", [NSString stringWithFormat: format, ## __VA_ARGS__])

#define PREFS_PATH [NSString stringWithFormat:@"%@/Library/Preferences/com.alexzielenski.tinybar.plist", NSHomeDirectory()]
#define DEFAULT_DURATION 6.375
#define DEFAULT_DURATION_LONG 10.375
#define DEFAULT_SPEED 85.0
#define DEFAULT_HEIGHT 20.0
#define DEFAULT_ENABLED YES
#define DEFAULT_SHOWTITLE YES
#define DEFAULT_SHOWICON YES
#define DEFAULT_STRETCH_BANNER YES
#define DEFAULT_SCROLLTOEND YES
#define DEFAULT_STICKY NO
#define DEFAULT_SHOWCOLON NO

#define PREFS_DURATION_KEY @"duration"
#define PREFS_SPEED_KEY @"speed"
#define PREFS_HEIGHT_KEY @"height"
#define PREFS_ENABLED_KEY @"enabled"
#define PREFS_SHOWTITLE_KEY @"showTitle"
#define PREFS_DURATION_LONG_KEY @"durationLong"
#define PREFS_SHOWICON_KEY @"showIcon"
#define PREFS_STRETCH_BANNER_KEY @"stretchBanner"
#define PREFS_SCROLLTOEND_KEY @"scrollToEnd"
#define PREFS_STICKY_KEY @"sticky"
#define PREFS_FONT_KEY @"font"
#define PREFS_MESSAGEFONT_KEY @"messageFont"
#define PREFS_SHOWCOLON_KEY @"showColon"

#define DEFAULT_PREFS [NSDictionary dictionaryWithObjectsAndKeys: @DEFAULT_SHOWCOLON, PREFS_SHOWCOLON_KEY, @DEFAULT_STICKY, PREFS_STICKY_KEY, @DEFAULT_SCROLLTOEND, PREFS_SCROLLTOEND_KEY, @DEFAULT_STRETCH_BANNER, PREFS_STRETCH_BANNER_KEY, @DEFAULT_SHOWICON, PREFS_SHOWICON_KEY, @DEFAULT_DURATION_LONG, PREFS_DURATION_LONG_KEY, @DEFAULT_SHOWTITLE, PREFS_SHOWTITLE_KEY, @DEFAULT_DURATION, PREFS_DURATION_KEY, @DEFAULT_SPEED, PREFS_SPEED_KEY, @DEFAULT_HEIGHT, PREFS_HEIGHT_KEY, @DEFAULT_ENABLED, PREFS_HEIGHT_KEY, nil]